### ISSUE TITLE
Error when enabling Production/disable Sandbox

### ISSUE THREAD

**Issue by ghost** [MOLPay/molpay-mobile-xdk-flutter-beta#10]
Hi, I am getting the error below when disabling the sandbox

![image](https://user-images.githubusercontent.com/25141264/96223566-bcc38600-0fc0-11eb-82c4-77e84e1eca9e.png)

please advice. TQ

**Comment by hisyamadzha** [comment]
Hi @ammard2u ,
You might need to change your api credential as well, not just make 'mp_dev_mode' to false.
To use full service of the xdk, you need a valid;
- username
- password
- verification key
- 'mp_dev_mode' = false (Using development account) and 'mp_dev_mode' = true (Using production account)

**Comment by ghost** [comment]
Hi @hisyamadzha yes. i use all the valid details from Android app setting (we have production app in android). still getting the error

enabling the mp_dev_mode = true and sandbox = false also getting the same issue

**Comment by hisyamadzha** [comment]
@ammard2u, means this is your 1st time encounter such error?
Please report this issue to our support at support-sa@razer.com and our support will prompt accordingly.

**Comment by ghost** [comment]
first time in flutter sdk. sandbox is ok. just the production part is not ok

**Comment by hisyamadzha** [comment]
Yes, sandbox is just a offline mockup response done by the app and not connected to RMS server.
