### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by juliocbcotta** [MOLPay/molpay-mobile-xdk-flutter-beta#2]
Hey, how about to migrate to AndroidX libraries?

**Comment by IzzatyAnuar** [comment]
We don't support AndroidX as it is an optional for user, we will only maintain the pure lib. You can fork our repo then do AndroidX lib by your own.

**Comment by juliocbcotta** [comment]
There is no such thing as pure library, you are using very old (more than 2 years old) support libraries.
All android development should be done with Android X and you are just keeping your users back in time.

**Comment by clewlb** [comment]
@BugsBunnyBR Thanks for your feedback. Due to legacy support, we will wait until Google Play minimum updates API level set to 28 before we can migrate to the new Android Jetpack. Do watch this repo for latest updates.
