### ISSUE TITLE
Keep crashing in android devices when closing payment window

### ISSUE THREAD

**Issue by Tyfoo16** [MOLPay/molpay-mobile-xdk-flutter-beta#6]
I have built the android flutter project with molpay xdk and try to make the payment in real android devices. It crashed when I close the payment window, made successful payment and any other actions that involve closing the payment window. 

**Crash log :**

`
I/chromium(19512): [INFO:CONSOLE(19)] "Uncaught ReferenceError: module is not defined", source: file:///android_asset/molpay-mobile-xdk-www/scripts/vendor.993ae4d8.js (19)
D/MOLPAY  (19512): MPMainUIWebClient onPageFinished paymentDetails = {"mp_username":"api_airhopp","mp_channel_editing":true,"mp_allowed_channels":["fpx","cash","RazerPay","TNG-EWALLET","BOOST"],"mp_amount":1.01,"mp_country":"MY","mp_password":"api_HaKK*&15","wrapper_version":"0.0","mp_verification_key":"9a861000a335fb1e22a4dc0f20c4b4f6","mp_bill_mobile":"0172838127","mp_bill_email":"michaelgard16@gmail.com","mp_order_ID":"A5E6D22749F4FE","mp_credit_card_expiry":null,"mp_merchant_ID":"airhopp","module_id":"molpay-mobile-xdk-flutter-beta-android","mp_credit_card_no":null,"mp_bill_description":"Airhopp payment","mp_channel":"","is_submodule":true,"mp_credit_card_cvv":null,"mp_app_name":"airhopp","mp_bill_name":"Michael","mp_editing_enabled":false,"mp_currency":"MYR"}
W/libEGL  (19512): EGLNativeWindowType 0x7c3288c010 disconnect failed
D/FlutterView(19512): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@23cb9e9
W/libEGL  (19512): EGLNativeWindowType 0x7bfb7ea010 disconnect failed
W/irhopp_custome(19512): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/libEGL  (19512): EGLNativeWindowType 0x7c91a30350 disconnect failed
W/irhopp_custome(19512): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/Settings(19512): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(19512): User setup is finished.
V/AudioManager(19512): querySoundEffectsEnabled...
D/MOLPAY  (19512): MPMainUIWebClient shouldOverrideUrlLoading url = mpcloseallwindows://
W/cr_AwContents(19512): WebView.destroy() called while WebView is still attached to window.
D/MOLPAY  (19512): MPMainUIWebClient shouldOverrideUrlLoading url = mptransactionresults://eyJ0eG5fSUQiOiIxOTk0OTE2NzQiLCJwYXlkYXRlIjoxNTg0MjEyMzc1LCJvcmRlcl9pZCI6IkE1RTZEMjI3NDlGNEZFIiwiYW1vdW50IjoiMS4wMSIsInN0YXR1c19jb2RlIjoiMjIiLCJjaGFubmVsIjoiVE5HLUVXQUxMRVQiLCJlcnJfZGVzYyI6IiIsImFwcF9jb2RlIjoiIiwiY2hrc3VtIjoiZmEzMDg4MDAwNjQ4ZTI3NTdhMTkwNjQwZWU2OWNkOGMiLCJwSW5zdHJ1Y3Rpb24iOjAsIm1zZ1R5cGUiOiJEOCIsIm1wX3NlY3VyZWRfdmVyaWZpZWQiOmZhbHNlfQ==
D/MOLPAY  (19512): MPMainUIWebClient mptransactionresults base64String = eyJ0eG5fSUQiOiIxOTk0OTE2NzQiLCJwYXlkYXRlIjoxNTg0MjEyMzc1LCJvcmRlcl9pZCI6IkE1RTZEMjI3NDlGNEZFIiwiYW1vdW50IjoiMS4wMSIsInN0YXR1c19jb2RlIjoiMjIiLCJjaGFubmVsIjoiVE5HLUVXQUxMRVQiLCJlcnJfZGVzYyI6IiIsImFwcF9jb2RlIjoiIiwiY2hrc3VtIjoiZmEzMDg4MDAwNjQ4ZTI3NTdhMTkwNjQwZWU2OWNkOGMiLCJwSW5zdHJ1Y3Rpb24iOjAsIm1zZ1R5cGUiOiJEOCIsIm1wX3NlY3VyZWRfdmVyaWZpZWQiOmZhbHNlfQ==
D/MOLPAY  (19512): MPMainUIWebClient mptransactionresults dataString = {"txn_ID":"199491674","paydate":1584212375,"order_id":"A5E6D22749F4FE","amount":"1.01","status_code":"22","channel":"TNG-EWALLET","err_desc":"","app_code":"","chksum":"fa3088000648e2757a190640ee69cd8c","pInstruction":0,"msgType":"D8","mp_secured_verified":false}
D/MOLPAY  (19512): MPMainUIWebClient jsonResult = {"txn_ID":"199491674","paydate":1584212375,"order_id":"A5E6D22749F4FE","amount":"1.01","status_code":"22","channel":"TNG-EWALLET","err_desc":"","app_code":"","chksum":"fa3088000648e2757a190640ee69cd8c","pInstruction":0,"msgType":"D8","mp_secured_verified":false}
I/BlockMonitor(19512): dispatchingThrewException In MainThread
D/AndroidRuntime(19512): Shutting down VM
I/QarthLog(19512): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(19512): [PatchStore] create disable file for com.airhopp.airhopp_customer uid is 10285
E/AndroidRuntime(19512): FATAL EXCEPTION: main
E/AndroidRuntime(19512): Process: com.airhopp.airhopp_customer, PID: 19512
E/AndroidRuntime(19512): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9999, result=-1, data=Intent { (has extras) }} to activity {com.airhopp.airhopp_customer/com.airhopp.airhopp_customer.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(19512): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5449)
E/AndroidRuntime(19512): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5490)
E/AndroidRuntime(19512): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(19512): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(19512): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/AndroidRuntime(19512): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
E/AndroidRuntime(19512): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19512): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(19512): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
E/AndroidRuntime(19512): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19512): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(19512): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(19512): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(19512): 	at com.molpay.molpaymobilexdkflutterbeta.MolpayMobileXdkFlutterBetaPlugin.onActivityResult(MolpayMobileXdkFlutterBetaPlugin.java:81)
E/AndroidRuntime(19512): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(19512): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(19512): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(19512): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(19512): 	at android.app.Activity.dispatchActivityResult(Activity.java:8393)
E/AndroidRuntime(19512): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5442)
E/AndroidRuntime(19512): 	... 11 more
I/Process (19512): Sending signal. PID: 19512 SIG: 9
Lost connection to device.
Exited (sigterm)
`

**Comment by AfiqRazer** [comment]
Hi there, the crash caused by flutter issue, what can I advise you now is please change/upgrade your flutter version or use v1.14.6 on BETA channel.
